const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const token=()=>crypto.randomUUID().replaceAll('-','');
const roomCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');
async function ensureDb(db){await db.prepare(`CREATE TABLE IF NOT EXISTS rooms (code TEXT PRIMARY KEY, host_token TEXT NOT NULL, guest_token TEXT, host_state TEXT NOT NULL DEFAULT '{}', guest_state TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'waiting', deadline INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`).run()}
const parse=async request=>{try{return await request.json()}catch{return {}}};
export default {async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);if(!env.DB)return json({error:'Serviço de salas indisponível.'},503);await ensureDb(env.DB);const parts=url.pathname.split('/').filter(Boolean),now=Date.now();
  if(request.method==='POST'&&url.pathname==='/api/rooms'){for(let tries=0;tries<5;tries++){const code=roomCode(),hostToken=token();try{await env.DB.prepare('INSERT INTO rooms (code,host_token,created_at,updated_at) VALUES (?,?,?,?)').bind(code,hostToken,now,now).run();return json({code,token:hostToken,role:'host'})}catch{}}return json({error:'Não foi possível criar a sala.'},500)}
  if(parts[0]==='api'&&parts[1]==='rooms'&&parts[2]){const code=parts[2].toUpperCase(),room=await env.DB.prepare('SELECT * FROM rooms WHERE code=?').bind(code).first();if(!room)return json({error:'Sala não encontrada.'},404);
    if(request.method==='POST'&&parts[3]==='join'){if(room.guest_token)return json({error:'A sala já possui dois jogadores.'},409);const guestToken=token(),deadline=now+120000,result=await env.DB.prepare("UPDATE rooms SET guest_token=?,status='drafting',deadline=?,updated_at=? WHERE code=? AND guest_token IS NULL").bind(guestToken,deadline,now,code).run();if(!result.meta?.changes)return json({error:'Outro jogador entrou primeiro.'},409);return json({code,token:guestToken,role:'guest',deadline})}
    const supplied=request.headers.get('x-room-token')||url.searchParams.get('token');const role=supplied===room.host_token?'host':supplied===room.guest_token?'guest':null;if(!role)return json({error:'Acesso inválido.'},403);
    if(request.method==='PUT'&&parts[3]==='state'){const body=await parse(request),field=role==='host'?'host_state':'guest_state',safe={formation:body.formation||null,lineupIds:Array.isArray(body.lineupIds)?body.lineupIds.slice(0,11):[],progress:Math.min(11,Number(body.progress)||0),coach:String(body.coach||'').slice(0,60),finished:Boolean(body.finished)};await env.DB.prepare(`UPDATE rooms SET ${field}=?,updated_at=? WHERE code=?`).bind(JSON.stringify(safe),now,code).run();return json({ok:true})}
    if(request.method==='GET'){const fresh=await env.DB.prepare('SELECT * FROM rooms WHERE code=?').bind(code).first(),decode=value=>{try{return JSON.parse(value||'{}')}catch{return {}}},host=decode(fresh.host_state),guest=decode(fresh.guest_state),reveal=Boolean(host.finished&&guest.finished)||Boolean(fresh.deadline&&fresh.deadline<=now),publicState=state=>reveal?state:{formation:state.formation||null,progress:state.progress||0,finished:Boolean(state.finished)};return json({code,status:fresh.status,deadline:fresh.deadline,connected:Boolean(fresh.guest_token),you:role,host:role==='host'?host:publicState(host),guest:role==='guest'?guest:publicState(guest),serverTime:now})}
  }return json({error:'Rota inválida.'},404)}};
